### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by pinpom** [vaanforz/Foodlg-Rafiki-Replacement#3]
API failed for end point "model/predict".
1) Run on AmazonAWS with instance:
- Instance Type: t2.2xlarge
- vCPUs: 8
- Memory (GiB): 16
- SSD: 64G
2) Environment:
- Ubuntu 16.04.6 LTS
- Docker version 19.03.8, build afacb8b7f0
- git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)
3) Commands & Error message:
$ `git clone https://github.com/vaanforz/Foodlg-Rafiki-Replacement.git`
$ `cd Foodlg-Rafiki-Replacement/`
$  `docker build -t foodlg_flask .`
$  `docker run --name foodlg-flask-container -d -p 5000:5000 foodlg_flask`

* Added image file ‘dinner.jpeg’ to the working directory
$ `curl -F "image=dinner.jpeg" -XPOST http://ec2-18-140-246-196.ap-southeast-1.compute.amazonaws.com:5000/model/predict`
```
aws.com:5000/model/predict
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

* Note: endpoint "/" is working with message: " Flask app has started successfully! ". 
I attached herewith the screenshot of the web UI
<img width="855" alt="Screenshot 2020-03-17 at 11 15 02 PM" src="https://user-images.githubusercontent.com/49071226/76873790-323f6a80-68a9-11ea-9475-74772a6f96ee.png">

**Comment by vaanforz** [comment]
you did not include the '@' symbol, should be:
curl -F "image=@dinner.jpeg" -XPOST http://ec2-18-140-246-196.ap-southeast-1.compute.amazonaws.com:5000/model/predict
